package com.test.zoom.service.journal;

import com.test.zoom.dto.Search;
import com.test.zoom.dto.journal.JournalSource;
import com.test.zoom.dto.journal.request.JournalSearchRequest;
import com.test.zoom.dto.journal.response.JournalDetailResponse;
import com.test.zoom.dto.journal.response.JournalLineResponse;
import com.test.zoom.dto.journal.response.JournalResponse;
import com.test.zoom.entity.journal.Account;
import com.test.zoom.entity.journal.JournalEntry;
import com.test.zoom.entity.journal.JournalLine;
import com.test.zoom.repository.journal.JournalEntryRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.util.List;

@Service
@RequiredArgsConstructor
public class JournalQueryServiceImpl implements JournalQueryService {

    private final JournalEntryRepository journalEntryRepository;

    @Override
    public List<JournalEntry> searchTest(Search search) {
        List<JournalEntry> list = journalEntryRepository.findByEntryDateBetweenAndDeletedFalse(search.getStartDate(), search.getEndDate());
        return list;
    }

    @Override
    public Page<JournalResponse> search(JournalSearchRequest request) {
        JournalEntry.Source entitySource = request.getSource() != null
                ? JournalEntry.Source.valueOf(request.getSource().name())
                : null;

        Specification<JournalEntry> spec = Specification
                .where(JournalEntrySpecifications.notDeleted())
                .and(JournalEntrySpecifications.entryDateBetween(request.getFromDate(), request.getToDate()))
                .and(JournalEntrySpecifications.vendorLike(request.getVendor()))
                .and(JournalEntrySpecifications.memberTagEquals(request.getMemberTag()))
                .and(JournalEntrySpecifications.sourceEquals(entitySource))
                .and(JournalEntrySpecifications.confirmedEquals(request.getConfirmed()))
                .and(JournalEntrySpecifications.accountIdEquals(request.getAccountId()))
                .and(JournalEntrySpecifications.amountBetween(request.getMinAmount(), request.getMaxAmount()));

        PageRequest pageRequest = PageRequest.of(
                request.getPage() != null ? request.getPage() : 0,
                request.getSize() != null ? request.getSize() : 20,
                Sort.by(Sort.Direction.DESC, "entryDate"));

        Page<JournalEntry> page = journalEntryRepository.findAll(spec, pageRequest);
        return page.map(this::toResponse);
    }

    @Override
    public JournalDetailResponse getDetail(Long id) {
        JournalEntry entry = journalEntryRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("전표가 존재하지 않습니다. id=" + id));

        List<JournalLineResponse> lineResponses = entry.getLines().stream()
                .map(this::toLineResponse)
                .toList();

        BigDecimal totalDebit = entry.getLines().stream()
                .map(JournalLine::getDebitAmount)
                .filter(java.util.Objects::nonNull)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        BigDecimal totalCredit = entry.getLines().stream()
                .map(JournalLine::getCreditAmount)
                .filter(java.util.Objects::nonNull)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        JournalDetailResponse response = new JournalDetailResponse();
        response.setId(entry.getId());
        response.setEntryDate(entry.getEntryDate());
        response.setDescription(entry.getDescription());
        response.setVendor(entry.getVendor());
        response.setMemberTag(entry.getMemberTag());
        response.setSource(JournalSource.valueOf(entry.getSource().name()));
        response.setAutoGenerated(entry.getSource() != JournalEntry.Source.MANUAL);
        response.setConfirmed(entry.isConfirmed());
        response.setConfirmedAt(entry.getConfirmedAt());
        response.setLines(lineResponses);
        response.setTotalDebit(totalDebit);
        response.setTotalCredit(totalCredit);
        return response;
    }

    private JournalResponse toResponse(JournalEntry entry) {
        BigDecimal amount = entry.getLines().stream()
                .map(JournalLine::getDebitAmount)
                .filter(d -> d != null && d.signum() > 0)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        return new JournalResponse(
                entry.getId(),
                entry.getEntryDate(),
                entry.getDescription(),
                entry.getVendor(),
                entry.getMemberTag(),
                JournalSource.valueOf(entry.getSource().name()),
                entry.getSource() != JournalEntry.Source.MANUAL,
                entry.isConfirmed(),
                amount
        );
    }

    private JournalLineResponse toLineResponse(JournalLine line) {
        Account account = line.getAccount();
        return new JournalLineResponse(
                line.getId(),
                account.getId(),
                account.getCode(),
                account.getName(),
                line.getDebitAmount(),
                line.getCreditAmount(),
                line.getMemo()
        );
    }

}