spring.application.name=zoom

server.port=9090

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:file:./data/authdb;AUTO_SERVER=TRUE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=ad
#spring.datasource.password=pw

spring.datasource.driver-class-name=com.p6spy.engine.spy.P6SpyDriver
spring.datasource.url=jdbc:p6spy:mariadb://192.168.2.220:3306/hab2
spring.datasource.username=arisys
spring.datasource.password=Arisys123$
spring.datasource.connection-init-sql=SELECT 1 FROM DUAL

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

logging.level.org.springframework=info
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

jwt.header=Authorization
jwt.secret=JDJhJDEzJEdIUmcuQ1FrQ2lNazFFUkpySGNqVHU1emR3M08zSHB3TVRCVGZvc1c5VlE2NEtzZ0ZPa20yJDJhJDEzJEdIUmcuQ1FrQ2lNazFFUkpySGNqVHU1emR3M08zSHB3TVRCVGZvc1c5VlE2NEtzZ0ZPa20y
jwt.token-validity-in-seconds=86400000

#sever.port=443
#server.ssl.key-store=/Users/jisu/Desktop/dev/certs/certbot
#server.ssl.key-store-password=asem11ble
#server.ssl.key-store-type=PKCS12