
import type { Menu, Code, ZoomPhone, departmentCall } from '@/types/apps/SampleType.ts';

const MenuDatatables: Menu[] = [
    {
        id: '1',
        menuid: 'MENU001',
        main: 'HOME',
        url: '/home/dashboard',
        sub: 'Dashboard',
        imagename: 'image1',
        sortid: '1',
        selectable: false,
    },
    {
        id: '2',
        menuid: 'MENU002',
        main: '사용자 및 조직',
        url: '/user/profile',
        sub: '사용자',
        imagename: 'image2',
        sortid: '2',
        selectable: false,
    },
    {
        id: '3',
        menuid: 'MENU003',
        main: '사용자 및 조직',
        url: '/user/organization',
        sub: '조직',
        imagename: 'image3',
        sortid: '3',
        selectable: false,
    },
    {
        id: '4',
        menuid: 'MENU004',
        main: '사용자 및 조직',
        url: '/user/phone',
        sub: '폰 사용자',
        imagename: 'image4',
        sortid: '4',
        selectable: false,
    },
    {
        id: '5',
        menuid: 'MENU005',
        main: '폰',
        url: '/phone/device',
        sub: '디바이스',
        imagename: 'image5',
        sortid: '5',
        selectable: false,
    },
    {
        id: '6',
        menuid: 'MENU006',
        main: '폰',
        url: '/phone/extension',
        sub: '내선번호',
        imagename: 'image6',
        sortid: '6',
        selectable: false,
    },
    {
        id: '7',
        menuid: 'MENU007',
        main: '폰',
        url: '/phone/pstn',
        sub: 'PSTN',
        imagename: 'image7',
        sortid: '7',
        selectable: false,
    },
    {
        id: '8',
        menuid: 'MENU008',
        main: '폰',
        url: '/phone/pickup/group',
        sub: '당겨받기 그룹',
        imagename: 'image8',
        sortid: '8',
        selectable: false,
    },
    {
        id: '9',
        menuid: 'MENU009',
        main: '폰',
        url: '/phone/billing',
        sub: '과금',
        imagename: 'image9',
        sortid: '9',
        selectable: false,
    },
    {
        id: '10',
        menuid: 'MENU010',
        main: '폰',
        url: '/phone/recording',
        sub: '녹취',
        imagename: 'image10',
        sortid: '10',
        selectable: false,
    },
    {
        id: '11',
        menuid: 'MENU011',
        main: '디바이스 현황',
        url: '/device/phone',
        sub: '폰 디바이스 현황',
        imagename: 'image11',
        sortid: '11',
        selectable: false,
    },
    {
        id: '12',
        menuid: 'MENU012',
        main: '디바이스 현황',
        url: '/device/sbc',
        sub: 'SBC 현황',
        imagename: 'image12',
        sortid: '12',
        selectable: false,
    },
];

const CodeDatatables: Code []= [
    {
        id: "1",
        codename: "영업본부",
        maincode: "0001",
        etccode1: "0001",
        etccode2: "001",
        changecode: "Y",
        usingcode: "Y",
    },
    {
        id: "2",
        codename: "고객지원본부",
        maincode: "0002",
        etccode1: "0002",
        etccode2: "002",
        changecode: "N",
        usingcode: "Y",
    },
    {
        id: "3",
        codename: "경영지원",
        maincode: "0003",
        etccode1: "0003",
        etccode2: "003",
        changecode: "Y",
        usingcode: "Y",
    },
    {
        id: "4",
        codename: "기술연구소",
        maincode: "0004",
        etccode1: "0004",
        etccode2: "004",
        changecode: "N",
        usingcode: "Y",
    },

];

const ZoomPhoneDatatables: ZoomPhone[] = [
    {
        phoneName: "Phone1",
        user: "조정석",
        phoneNum: "308151",
        pstnNum: "02-2177-8152",
        phoneStatus: "Online",
        manufacturer: "Avaya",
        modelName: "J159",
        macAddress: "c8-1f-ea-d7-a1-f6",
        firmware: "4.1.3.0.6",
        publicAddress: "211.xxx.xxx.xxx",
        privateAddress: "192.168.101.51",
        assignmentType: "사용자",
        assignmentTarget: "조정석"
    },
    {
        phoneName: "Phone2",
        user: "정아람",
        phoneNum: "308152",
        pstnNum: "02-2177-8153",
        phoneStatus: "Online",
        manufacturer: "Avaya",
        modelName: "J139",
        macAddress: "c8-1f-ea-d7-a1-f7",
        firmware: "4.1.3.0.6",
        publicAddress: "211.xxx.xxx.xxx",
        privateAddress: "192.168.101.52",
        assignmentType: "CAP",
        assignmentTarget: "308152"
    },
    {
        phoneName: "Phone3",
        user: "최민식",
        phoneNum: "308153",
        pstnNum: "02-2177-8154",
        phoneStatus: "Online",
        manufacturer: "Avaya",
        modelName: "J179",
        macAddress: "c8-1f-ea-d7-a1-f8",
        firmware: "4.1.3.0.6",
        publicAddress: "211.xxx.xxx.xxx",
        privateAddress: "192.168.101.53",
        assignmentType: "사용자",
        assignmentTarget: "최민식"
    },
    {
        phoneName: "Phone4",
        user: "이재욱",
        phoneNum: "308154",
        pstnNum: "02-2177-8155",
        phoneStatus: "Online",
        manufacturer: "Avaya",
        modelName: "J139",
        macAddress: "c8-1f-ea-d7-a1-f9",
        firmware: "4.1.3.0.6",
        publicAddress: "211.xxx.xxx.xxx",
        privateAddress: "192.168.101.54",
        assignmentType: "CAP",
        assignmentTarget: "308154"
    },
];


const DepartmentCallDatatables: departmentCall []= [
    {
        date: "2025-03-11",
        dept: "영업본부",
        team: "영업1팀",
        phonecase: "핸드폰",
        calltotal: "6",
        totaltime: "00:12:11",
        inCalltotal:  "19",
        inTotaltime: "00:17:11",
    },
    {
        date: "2025-03-12",
        dept: "영업본부",
        team: "영업1팀",
        phonecase: "시내/시외",
        calltotal: "4",
        totaltime: "00:12:12",
        inCalltotal:  "21",
        inTotaltime: "00:12:11",
    },
    {
        date: "2025-03-13",
        dept: "영업본부",
        team: "영업1팀",
        phonecase: "국제전화",
        calltotal: "8",
        totaltime: "00:12:13",
        inCalltotal:  "6",
        inTotaltime: "00:12:56",
    },
    {
        date: "2025-03-14",
        dept: "영업본부",
        team: "영업1팀",
        phonecase: "특수번호",
        calltotal: "7",
        totaltime: "00:12:14",
        inCalltotal:  "6",
        inTotaltime: "00:13:12",
    },
    {
        date: "2025-03-15",
        dept: "경영지원",
        team: "경영지원팀",
        phonecase: "핸드폰",
        calltotal: "9",
        totaltime: "00:12:11",
        inCalltotal:  "8",
        inTotaltime: "00:16:17",
    },
    {
        date: "2025-03-15",
        dept: "경영지원",
        team: "경영지원팀",
        phonecase: "시내/시외",
        calltotal: "2",
        totaltime: "00:12:11",
        inCalltotal:  "5",
        inTotaltime: "00:12:10",
    },
    {
        date: "2025-03-15",
        dept: "경영지원",
        team: "경영지원팀",
        phonecase: "국제전화",
        calltotal: "3",
        totaltime: "00:15:11",
        inCalltotal:  "19",
        inTotaltime: "00:13:41",
    },
    {
        date: "2025-03-15",
        dept: "경영지원",
        team: "경영지원팀",
        phonecase: "특수번호",
        calltotal: "5",
        totaltime: "00:11:14",
        inCalltotal:  "11",
        inTotaltime: "00:16:11",
    },
];

export {MenuDatatables, CodeDatatables, ZoomPhoneDatatables, DepartmentCallDatatables};
