// ── 대차대조표 / 손익계산서 ──────────────────────────────
export interface AccountBalanceItem {
    accountId: number;
    code: string;
    name: string;
    parentId: number | null;
    depth: number;
    confirmedAmount: number;
    unconfirmedAmount: number;
    totalAmount: number;
    leaf: boolean;
}

export interface BalanceSheetResponse {
    asOfDate: string;
    assets: AccountBalanceItem[];
    liabilities: AccountBalanceItem[];
    totalAssets: number;
    totalLiabilities: number;
    equity: number;
    totalAssetsConfirmedOnly: number;
    totalLiabilitiesConfirmedOnly: number;
    equityConfirmedOnly: number;
    balanced: boolean;
}

export interface IncomeStatementResponse {
    fromDate: string;
    toDate: string;
    revenues: AccountBalanceItem[];
    expenses: AccountBalanceItem[];
    totalRevenue: number;
    totalExpense: number;
    netIncome: number;
}

// ── 전표 조회 / 수기입력 ──────────────────────────────
export interface AccountOption {
    id: number;
    code: string;
    name: string;
    category: 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'EXPENSE';
    parentId: number | null;
    leaf: boolean;
}

export type JournalSource = 'MANUAL' | 'CARD_IMPORT' | 'SETTLEMENT' | 'RECURRING';

export interface JournalListItem {
    id: number;
    entryDate: string;
    description: string | null;
    vendor: string | null;
    memberTag: string | null;
    source: JournalSource;
    autoGenerated: boolean;
    confirmed: boolean;
    amount: number;
}

export interface JournalLineItem {
    lineId: number;
    accountId: number;
    accountCode: string;
    accountName: string;
    debitAmount: number;
    creditAmount: number;
    memo: string | null;
}

export interface JournalDetail {
    id: number;
    entryDate: string;
    description: string | null;
    vendor: string | null;
    memberTag: string | null;
    source: JournalSource;
    autoGenerated: boolean;
    confirmed: boolean;
    confirmedAt: string | null;
    lines: JournalLineItem[];
    totalDebit: number;
    totalCredit: number;
}

export interface JournalLineForm {
    accountId: number | null;
    debitAmount: number | null;
    creditAmount: number | null;
    memo: string;
}

export interface PageResponse<T> {
    content: T[];
    totalElements: number;
    totalPages: number;
    number: number; // 현재 페이지(0-base)
    size: number;
}
