package com.test.zoom.dto.journal.request;

import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDate;

@Data
public class JournalSearchRequest {

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private LocalDate startDate;

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private LocalDate endDate;

    /** 계정과목 */
    private Long accountId;

    /** 거래처 */
    private String vendor;

    /** 구성원 */
    private String memberTag;

    /** 확정여부 */
    private Boolean confirmed;

    /** 자동분개 */
    private Boolean autoGenerated;

    /** 페이지 */
    private int page = 0;

    /** 페이지 크기 */
    private int size = 20;

}