<script setup lang="ts">
import UiParentCard from '@/components/shared/UiParentCard.vue';
import { computed, onMounted, ref } from 'vue';
import type { AccountOption, JournalLineForm } from '@/types/custom/JournalTypes';
import { apiClient } from '@/data/Axios';
import { format } from 'date-fns';
import { useRoute, useRouter } from 'vue-router';
import { parseExcel } from '@/common/excel/excelService'; // 기존 프로젝트 경로에 맞게 조정

const route = useRoute();
const router = useRouter();

const editId = computed(() => (route.query.id ? Number(route.query.id) : null));

const accounts = ref<AccountOption[]>([]);
const leafAccounts = computed(() => accounts.value.filter((a) => a.leaf));
const assetLeafAccounts = computed(() => leafAccounts.value.filter((a) => a.category === 'ASSET'));

const entryDate = ref(format(new Date(), 'yyyy-MM-dd'));
const description = ref('');
const vendor = ref('');
const memberTag = ref('');

const emptyLine = (): JournalLineForm => ({ accountId: null, debitAmount: null, creditAmount: null, memo: '' });
const lines = ref<JournalLineForm[]>([emptyLine(), emptyLine()]);

const errorMessage = ref('');
const saving = ref(false);

const totalDebit = computed(() => lines.value.reduce((sum, l) => sum + (Number(l.debitAmount) || 0), 0));
const totalCredit = computed(() => lines.value.reduce((sum, l) => sum + (Number(l.creditAmount) || 0), 0));
const isBalanced = computed(() => totalDebit.value === totalCredit.value && totalDebit.value > 0);

const addLine = () => lines.value.push(emptyLine());
const removeLine = (index: number) => {
    if (lines.value.length <= 2) return; // 최소 2줄(차변/대변) 유지
    lines.value.splice(index, 1);
};

const loadAccounts = async () => {
    accounts.value = await apiClient.get('/journal/accounts');
};

const loadForEdit = async (id: number) => {
    const detail = await apiClient.get(`/journal/entries/${id}`);
    if (detail.autoGenerated) {
        errorMessage.value = '자동생성된 전표는 이 화면에서 수정할 수 없습니다.';
        return;
    }
    entryDate.value = detail.entryDate;
    description.value = detail.description ?? '';
    vendor.value = detail.vendor ?? '';
    memberTag.value = detail.memberTag ?? '';
    lines.value = detail.lines.map((l: any) => ({
        accountId: l.accountId,
        debitAmount: l.debitAmount || null,
        creditAmount: l.creditAmount || null,
        memo: l.memo ?? ''
    }));
};

onMounted(async () => {
    await loadAccounts();
    if (editId.value) {
        await loadForEdit(editId.value);
    }
});

const validate = (): boolean => {
    errorMessage.value = '';

    if (!entryDate.value) {
        errorMessage.value = '전표일자를 입력해주세요.';
        return false;
    }

    for (const line of lines.value) {
        if (!line.accountId) {
            errorMessage.value = '모든 라인에 계정과목을 선택해주세요.';
            return false;
        }
        const debit = Number(line.debitAmount) || 0;
        const credit = Number(line.creditAmount) || 0;
        if (debit > 0 && credit > 0) {
            errorMessage.value = '한 라인에 차변과 대변을 동시에 입력할 수 없습니다.';
            return false;
        }
        if (debit === 0 && credit === 0) {
            errorMessage.value = '차변 또는 대변 금액을 입력해주세요.';
            return false;
        }
    }

    if (!isBalanced.value) {
        errorMessage.value = `차변합계(${totalDebit.value})와 대변합계(${totalCredit.value})가 일치하지 않습니다.`;
        return false;
    }

    return true;
};

const buildPayload = () => ({
    entryDate: entryDate.value,
    description: description.value || null,
    vendor: vendor.value || null,
    memberTag: memberTag.value || null,
    lines: lines.value.map((l) => ({
        accountId: l.accountId,
        debitAmount: l.debitAmount || 0,
        creditAmount: l.creditAmount || 0,
        memo: l.memo || null
    }))
});

const onSubmit = async () => {
    if (!validate()) return;

    saving.value = true;
    try {
        if (editId.value) {
            await apiClient.put(`/journal/entries/${editId.value}`, buildPayload());
        } else {
            await apiClient.post('/journal/entries', buildPayload());
        }
        router.push('/journal/list');
    } catch (e: any) {
        errorMessage.value = e?.response?.data?.message || '저장 중 오류가 발생했습니다.';
    } finally {
        saving.value = false;
    }
};

const onReset = () => {
    entryDate.value = format(new Date(), 'yyyy-MM-dd');
    description.value = '';
    vendor.value = '';
    memberTag.value = '';
    lines.value = [emptyLine(), emptyLine()];
    errorMessage.value = '';
};

// ────────────────────────────────────────────────────────────
// 은행 거래내역 엑셀 업로드 (미리보기 → 계정수정 → 일괄저장)
// ────────────────────────────────────────────────────────────
interface BankImportRowUi extends Record<string, any> {
    transactionDate: string;
    description: string;
    deposit: number | null;
    withdrawal: number | null;
    rawAccountInfo?: string;
    accountCode?: string; // 엑셀에서 미리 지정한 상대계정 코드 (선택) — 있으면 리졸버보다 우선 적용됨
    accountId: number | null;
    accountName?: string;
    duplicate: boolean;
    skip: boolean;
}

const showBankImport = ref(false);
const targetAccountId = ref<number | null>(null);
const bankImportFile = ref<File | null>(null);
const previewRows = ref<BankImportRowUi[]>([]);
const previewing = ref(false);
const bankSaving = ref(false);
const bankErrorMessage = ref('');
const bankResultMessage = ref('');

const previewHeaders = ref<any[]>([
    { title: '거래일자', align: 'start', key: 'transactionDate' },
    { title: '적요', align: 'start', key: 'description' },
    { title: '입금', align: 'end', key: 'deposit' },
    { title: '출금', align: 'end', key: 'withdrawal' },
    { title: '상대계정', align: 'start', key: 'accountId' },
    { title: '중복', align: 'center', key: 'duplicate' },
    { title: '제외', align: 'center', key: 'skip' }
]);

const onBankFileChange = (files: File[] | File | null) => {
    bankImportFile.value = Array.isArray(files) ? (files[0] ?? null) : files;
};

const onPreview = async () => {
    bankErrorMessage.value = '';
    bankResultMessage.value = '';

    if (!targetAccountId.value) {
        bankErrorMessage.value = '대상 계좌(예: 국민은행, 신한은행)를 먼저 선택해주세요.';
        return;
    }
    if (!bankImportFile.value) {
        bankErrorMessage.value = '엑셀 파일을 선택해주세요.';
        return;
    }

    previewing.value = true;
    try {
        const parsed = await parseExcel<BankImportRowUi>(bankImportFile.value);
        const response = await apiClient.post('/journal/entries/bank-import/preview', {
            targetAccountId: targetAccountId.value,
            rows: parsed
        });
        previewRows.value = response;
    } catch (e: any) {
        bankErrorMessage.value = e?.response?.data?.message || '미리보기 처리 중 오류가 발생했습니다.';
    } finally {
        previewing.value = false;
    }
};

const onBankSave = async () => {
    bankErrorMessage.value = '';
    bankResultMessage.value = '';

    // 저장 전 화면단 검증: 계정 미선택 행이 있는지
    const missing = previewRows.value.filter((r) => !r.skip && !r.accountId);
    if (missing.length > 0) {
        bankErrorMessage.value = `상대계정이 선택되지 않은 행이 ${missing.length}건 있습니다. 확인해주세요.`;
        return;
    }

    bankSaving.value = true;
    try {
        const result = await apiClient.post('/journal/entries/bank-import/save', {
            targetAccountId: targetAccountId.value,
            rows: previewRows.value
        });
        bankResultMessage.value = `${result.savedCount}건 저장, ${result.skippedCount}건 제외 완료.`;
        previewRows.value = [];
        bankImportFile.value = null;
    } catch (e: any) {
        bankErrorMessage.value = e?.response?.data?.message || '저장 중 오류가 발생했습니다.';
    } finally {
        bankSaving.value = false;
    }
};
</script>

<template>
    <v-row>
        <v-col cols="12">
            <UiParentCard :title="editId ? '전표 수정' : '전표 수기입력'">
                <v-alert v-if="errorMessage" type="error" variant="tonal" density="compact" class="mb-4">
                    {{ errorMessage }}
                </v-alert>

                <v-row>
                    <v-col cols="12" md="3">
                        <v-text-field v-model="entryDate" label="전표일자" type="date" density="compact" />
                    </v-col>
                    <v-col cols="12" md="3">
                        <v-text-field v-model="description" label="적요" density="compact" />
                    </v-col>
                    <v-col cols="12" md="3">
                        <v-text-field v-model="vendor" label="거래처" density="compact" />
                    </v-col>
                    <v-col cols="12" md="3">
                        <v-text-field v-model="memberTag" label="가족태그" density="compact" />
                    </v-col>
                </v-row>

                <v-row>
                    <v-col cols="12">
                        <div class="d-flex justify-space-between align-center mb-2">
                            <h3>분개라인</h3>
                            <v-btn size="small" color="primary" variant="outlined" @click="addLine">라인 추가</v-btn>
                        </div>

                        <v-table density="compact">
                            <thead>
                            <tr>
                                <th style="width: 30%">계정과목</th>
                                <th style="width: 18%" class="text-end">차변</th>
                                <th style="width: 18%" class="text-end">대변</th>
                                <th style="width: 24%">메모</th>
                                <th style="width: 10%"></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr v-for="(line, idx) in lines" :key="idx">
                                <td>
                                    <v-select
                                        v-model="line.accountId"
                                        :items="leafAccounts"
                                        item-title="name"
                                        item-value="id"
                                        density="compact"
                                        hide-details
                                    />
                                </td>
                                <td>
                                    <v-text-field v-model.number="line.debitAmount" type="number" density="compact" hide-details />
                                </td>
                                <td>
                                    <v-text-field v-model.number="line.creditAmount" type="number" density="compact" hide-details />
                                </td>
                                <td>
                                    <v-text-field v-model="line.memo" density="compact" hide-details />
                                </td>
                                <td>
                                    <v-btn icon size="small" variant="text" color="error" @click="removeLine(idx)">
                                        <v-icon>mdi-close</v-icon>
                                    </v-btn>
                                </td>
                            </tr>
                            <tr class="font-weight-bold">
                                <td>합계</td>
                                <td class="text-end" :class="{ 'text-error': !isBalanced }">{{ totalDebit }}</td>
                                <td class="text-end" :class="{ 'text-error': !isBalanced }">{{ totalCredit }}</td>
                                <td colspan="2"></td>
                            </tr>
                            </tbody>
                        </v-table>
                    </v-col>
                </v-row>

                <v-row class="mt-4">
                    <v-col class="d-flex gap-3 justify-end">
                        <v-btn variant="outlined" @click="onReset">초기화</v-btn>
                        <v-btn color="primary" :loading="saving" @click="onSubmit">저장</v-btn>
                    </v-col>
                </v-row>
            </UiParentCard>
        </v-col>

        <!-- 은행 거래내역 엑셀 업로드 -->
        <v-col cols="12">
            <UiParentCard title="은행 거래내역 엑셀 업로드">
                <v-row>
                    <v-col cols="12">
                        <v-btn variant="text" @click="showBankImport = !showBankImport">
                            {{ showBankImport ? '접기' : '펼치기' }}
                        </v-btn>
                    </v-col>
                </v-row>

                <template v-if="showBankImport">
                    <v-alert v-if="bankErrorMessage" type="error" variant="tonal" density="compact" class="mb-3" style="white-space: pre-line">
                        {{ bankErrorMessage }}
                    </v-alert>
                    <v-alert v-if="bankResultMessage" type="success" variant="tonal" density="compact" class="mb-3">
                        {{ bankResultMessage }}
                    </v-alert>

                    <v-row>
                        <v-col cols="12" md="3">
                            <v-select
                                v-model="targetAccountId"
                                :items="assetLeafAccounts"
                                item-title="name"
                                item-value="id"
                                label="대상 계좌 (예: kb입출금)"
                                density="compact"
                            />
                        </v-col>
                        <v-col cols="12" md="5">
                            <v-file-input
                                label="은행 거래내역 엑셀"
                                accept=".xlsx,.xls"
                                density="compact"
                                prepend-icon="mdi-file-excel"
                                @update:model-value="onBankFileChange"
                            />
                        </v-col>
                        <v-col cols="12" md="2" class="d-flex align-center">
                            <v-btn color="primary" :loading="previewing" @click="onPreview">미리보기</v-btn>
                        </v-col>
                    </v-row>

                    <v-row v-if="previewRows.length > 0">
                        <v-col cols="12">
                            <v-data-table :headers="previewHeaders" :items="previewRows" items-per-page="-1" hide-default-footer class="border rounded-md">
                                <template #item.deposit="{ item }">{{ item.deposit ? item.deposit.toLocaleString() : '' }}</template>
                                <template #item.withdrawal="{ item }">{{ item.withdrawal ? item.withdrawal.toLocaleString() : '' }}</template>
                                <template #item.accountId="{ item }">
                                    <v-select
                                        v-model="item.accountId"
                                        :items="leafAccounts"
                                        item-title="name"
                                        item-value="id"
                                        density="compact"
                                        hide-details
                                    />
                                </template>
                                <template #item.duplicate="{ item }">
                                    <v-chip v-if="item.duplicate" color="warning" size="small">중복의심</v-chip>
                                </template>
                                <template #item.skip="{ item }">
                                    <v-checkbox v-model="item.skip" density="compact" hide-details />
                                </template>
                            </v-data-table>

                            <div class="d-flex justify-end mt-3">
                                <v-btn color="primary" :loading="bankSaving" @click="onBankSave">일괄저장</v-btn>
                            </div>
                        </v-col>
                    </v-row>
                </template>
            </UiParentCard>
        </v-col>
    </v-row>
</template>

<style scoped></style>