<script setup lang="ts">
import UiParentCard from '@/components/shared/UiParentCard.vue';
import { computed, onMounted, ref } from 'vue';
import type { AccountOption, JournalLineForm } from '@/types/custom/JournalTypes';
import { apiClient } from '@/data/Axios';
import { format } from 'date-fns';
import { useRoute, useRouter } from 'vue-router';

const route = useRoute();
const router = useRouter();

const editId = computed(() => (route.query.id ? Number(route.query.id) : null));

const accounts = ref<AccountOption[]>([]);
const leafAccounts = computed(() => accounts.value.filter((a) => a.leaf));

const entryDate = ref(format(new Date(), 'yyyy-MM-dd'));
const description = ref('');
const vendor = ref('');
const memberTag = ref('');

const emptyLine = (): JournalLineForm => ({ accountId: null, debitAmount: null, creditAmount: null, memo: '' });
const lines = ref<JournalLineForm[]>([emptyLine(), emptyLine()]);

const errorMessage = ref('');
const saving = ref(false);

const totalDebit = computed(() => lines.value.reduce((sum, l) => sum + (Number(l.debitAmount) || 0), 0));
const totalCredit = computed(() => lines.value.reduce((sum, l) => sum + (Number(l.creditAmount) || 0), 0));
const isBalanced = computed(() => totalDebit.value === totalCredit.value && totalDebit.value > 0);

const addLine = () => lines.value.push(emptyLine());
const removeLine = (index: number) => {
    if (lines.value.length <= 2) return; // 최소 2줄(차변/대변) 유지
    lines.value.splice(index, 1);
};

const loadAccounts = async () => {
    accounts.value = await apiClient.get('/journal/accounts');
};

const loadForEdit = async (id: number) => {
    const detail = await apiClient.get(`/journal/entries/${id}`);
    if (detail.autoGenerated) {
        errorMessage.value = '자동생성된 전표는 이 화면에서 수정할 수 없습니다.';
        return;
    }
    entryDate.value = detail.entryDate;
    description.value = detail.description ?? '';
    vendor.value = detail.vendor ?? '';
    memberTag.value = detail.memberTag ?? '';
    lines.value = detail.lines.map((l: any) => ({
        accountId: l.accountId,
        debitAmount: l.debitAmount || null,
        creditAmount: l.creditAmount || null,
        memo: l.memo ?? ''
    }));
};

onMounted(async () => {
    await loadAccounts();
    if (editId.value) {
        await loadForEdit(editId.value);
    }
});

const validate = (): boolean => {
    errorMessage.value = '';

    if (!entryDate.value) {
        errorMessage.value = '전표일자를 입력해주세요.';
        return false;
    }

    for (const line of lines.value) {
        if (!line.accountId) {
            errorMessage.value = '모든 라인에 계정과목을 선택해주세요.';
            return false;
        }
        const debit = Number(line.debitAmount) || 0;
        const credit = Number(line.creditAmount) || 0;
        if (debit > 0 && credit > 0) {
            errorMessage.value = '한 라인에 차변과 대변을 동시에 입력할 수 없습니다.';
            return false;
        }
        if (debit === 0 && credit === 0) {
            errorMessage.value = '차변 또는 대변 금액을 입력해주세요.';
            return false;
        }
    }

    if (!isBalanced.value) {
        errorMessage.value = `차변합계(${totalDebit.value})와 대변합계(${totalCredit.value})가 일치하지 않습니다.`;
        return false;
    }

    return true;
};

const buildPayload = () => ({
    entryDate: entryDate.value,
    description: description.value || null,
    vendor: vendor.value || null,
    memberTag: memberTag.value || null,
    lines: lines.value.map((l) => ({
        accountId: l.accountId,
        debitAmount: l.debitAmount || 0,
        creditAmount: l.creditAmount || 0,
        memo: l.memo || null
    }))
});

const onSubmit = async () => {
    if (!validate()) return;

    saving.value = true;
    try {
        if (editId.value) {
            await apiClient.put(`/journal/entries/${editId.value}`, buildPayload());
        } else {
            await apiClient.post('/journal/entries', buildPayload());
        }
        router.push('/journal/list');
    } catch (e: any) {
        errorMessage.value = e?.response?.data?.message || '저장 중 오류가 발생했습니다.';
    } finally {
        saving.value = false;
    }
};

const onReset = () => {
    entryDate.value = format(new Date(), 'yyyy-MM-dd');
    description.value = '';
    vendor.value = '';
    memberTag.value = '';
    lines.value = [emptyLine(), emptyLine()];
    errorMessage.value = '';
};
</script>

<template>
    <v-row>
        <v-col cols="12">
            <UiParentCard :title="editId ? '전표 수정' : '전표 수기입력'">
                <v-alert v-if="errorMessage" type="error" variant="tonal" density="compact" class="mb-4">
                    {{ errorMessage }}
                </v-alert>

                <v-row>
                    <v-col cols="12" md="3">
                        <v-text-field v-model="entryDate" label="전표일자" type="date" density="compact" />
                    </v-col>
                    <v-col cols="12" md="3">
                        <v-text-field v-model="description" label="적요" density="compact" />
                    </v-col>
                    <v-col cols="12" md="3">
                        <v-text-field v-model="vendor" label="거래처" density="compact" />
                    </v-col>
                    <v-col cols="12" md="3">
                        <v-text-field v-model="memberTag" label="가족태그" density="compact" />
                    </v-col>
                </v-row>

                <v-row>
                    <v-col cols="12">
                        <div class="d-flex justify-space-between align-center mb-2">
                            <h3>분개라인</h3>
                            <v-btn size="small" color="primary" variant="outlined" @click="addLine">라인 추가</v-btn>
                        </div>

                        <v-table density="compact">
                            <thead>
                                <tr>
                                    <th style="width: 30%">계정과목</th>
                                    <th style="width: 18%" class="text-end">차변</th>
                                    <th style="width: 18%" class="text-end">대변</th>
                                    <th style="width: 24%">메모</th>
                                    <th style="width: 10%"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="(line, idx) in lines" :key="idx">
                                    <td>
                                        <v-select
                                            v-model="line.accountId"
                                            :items="leafAccounts"
                                            item-title="name"
                                            item-value="id"
                                            density="compact"
                                            hide-details
                                        />
                                    </td>
                                    <td>
                                        <v-text-field v-model.number="line.debitAmount" type="number" density="compact" hide-details />
                                    </td>
                                    <td>
                                        <v-text-field v-model.number="line.creditAmount" type="number" density="compact" hide-details />
                                    </td>
                                    <td>
                                        <v-text-field v-model="line.memo" density="compact" hide-details />
                                    </td>
                                    <td>
                                        <v-btn icon size="small" variant="text" color="error" @click="removeLine(idx)">
                                            <v-icon>mdi-close</v-icon>
                                        </v-btn>
                                    </td>
                                </tr>
                                <tr class="font-weight-bold">
                                    <td>합계</td>
                                    <td class="text-end" :class="{ 'text-error': !isBalanced }">{{ totalDebit }}</td>
                                    <td class="text-end" :class="{ 'text-error': !isBalanced }">{{ totalCredit }}</td>
                                    <td colspan="2"></td>
                                </tr>
                            </tbody>
                        </v-table>
                    </v-col>
                </v-row>

                <v-row class="mt-4">
                    <v-col class="d-flex gap-3 justify-end">
                        <v-btn variant="outlined" @click="onReset">초기화</v-btn>
                        <v-btn color="primary" :loading="saving" @click="onSubmit">저장</v-btn>
                    </v-col>
                </v-row>
            </UiParentCard>
        </v-col>
    </v-row>
</template>

<style scoped></style>
