import type { UserItem, ZoomPhoneItem, RecordingItem } from '@/types/custom/DataTableTypes.ts'

// 사용자 데이터 리스트
const UserDataTables: UserItem[] = [
    {
        department: "고객지원본부",
        team: "기술1팀",
        username: "박OO",
        employeeId: "20019133",
        position: "사원",
        email: "happy@arisys.co.kr",
        zoomLicense: "Basic",
        phoneLicense: "",
    },
    {
        department: "고객지원본부",
        team: "기술2팀",
        username: "이OO",
        employeeId: "20355071",
        position: "대리",
        email: "good@arisys.co.kr",
        zoomLicense: "WorkplaceBiz",
        phoneLicense: "Phone Pro",
    },
    {
        department: "고객지원본부",
        team: "SPM팀",
        username: "최OO",
        employeeId: "20415072",
        position: "수석",
        email: "love@arisys.co.kr",
        zoomLicense: "WorkplaceBiz",
        phoneLicense: "Phone Pro",
    },
    {
        department: "고객지원본부",
        team: "기술1팀",
        username: "전OO",
        employeeId: "20680414",
        position: "과장",
        email: "joy@arisys.co.kr",
        zoomLicense: "WorkplaceBiz",
        phoneLicense: "Phone Pro, Power",
    },
];

const ZoomPhoneDataTables: ZoomPhoneItem[] = [
    {
        department: '고객지원본부',
        team: '기술1팀',
        username: '박OO',
        employeeId: '20019133',
        position: '사원',
        mobile: '02-2177-8151',
        pstnNumber: '•••',
        pullNumber: '기술2팀',
        ipPhone: 'Avaya J159_308152',
        zoomLicense: 'Phone Pro',
        callRecording: '선택녹취',
    },
    {
        department: '고객지원본부',
        team: '기술2팀',
        username: '이OO',
        employeeId: '20355071',
        position: '사원',
        mobile: '02-2177-8152',
        pstnNumber: '•••',
        pullNumber: '기술2팀',
        ipPhone: 'Avaya J159_308152',
        zoomLicense: 'Basic',
        callRecording: '선택녹취',
    },
    {
        department: '고객지원본부',
        team: 'SPM팀',
        username: '최OO',
        employeeId: '20415072',
        position: '사원',
        mobile: '02-2177-8153',
        pstnNumber: '•••',
        pullNumber: '기술2팀',
        ipPhone: 'Avaya J159_308152',
        zoomLicense: 'Phone Pro',
        callRecording: '전수녹취',
    },
    {
        department: '고객지원본부',
        team: '기술1팀',
        username: '전OO',
        employeeId: '20680414',
        position: '사원',
        mobile: '02-2177-8154',
        pstnNumber: '•••',
        pullNumber: '기술2팀',
        ipPhone: 'Avaya J159_308152',
        zoomLicense: 'Phone Pro',
        callRecording: '미사용',
    },
];


const RecordingDataTables : RecordingItem[] = [
    {
        type: "전수",
        direction: "아웃바운드",
        sender: "308151",
        receiver: "010-XXXX-XXXX",
        department: "고객지원본부",
        team: "기술1팀",
        username: "박○○",
        startTime: "2025-03-15T18:01",
        endTime: "2025-03-15T18:01",
        duration: "00:02:26",
        play: "Y",
        download: "연결",
        id: "1",
    },
    {
        type: "선택",
        direction: "인바운드",
        sender: "010-XXXX-XXXX",
        receiver: "308153",
        department: "고객지원본부",
        team: "SPM팀",
        username: "최○○",
        startTime: "2025-03-15T18:01",
        endTime: "2025-03-15T18:01",
        duration: "00:00:25",
        play: "N",
        download: "미응답",
        id: "2",
    },
    {
        type: "선택",
        direction: "인바운드",
        sender: "02-XXXX-XXXX",
        receiver: "308153",
        department: "고객지원본부",
        team: "SPM팀",
        username: "최○○",
        startTime: "2024-01-05T10:01",
        endTime: "2024-01-05T10:02",
        duration: "00:00:58",
        play: "N",
        download: "연결",
        id: "3",
    },
];

export { UserDataTables, ZoomPhoneDataTables, RecordingDataTables };
