package com.test.zoom.dto.journal.response;

import com.test.zoom.dto.journal.JournalSource;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;

/** 전표 목록(조회) 화면용 — 라인 상세 없이 대표 금액만 표시 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class JournalResponse {
    private Long id;
    private LocalDate entryDate;
    private String description;
    private String vendor;
    private String memberTag;
    private JournalSource source;

    /** source != MANUAL 인 경우 true — 화면에서 "자동생성" 뱃지 표시용 */
    private boolean autoGenerated;

    private boolean confirmed;

    /** 전표 대표 금액 (차변합계 = 대변합계, Service에서 SUM하여 세팅) */
    private BigDecimal amount;

}