package com.test.zoom.dto.journal.response;

import com.test.zoom.dto.journal.JournalSource;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/** 전표 상세(단건 조회/수정 화면)용 — 분개라인 전체 포함 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class JournalDetailResponse {
    private Long id;
    private LocalDate entryDate;
    private String description;
    private String vendor;
    private String memberTag;
    private JournalSource source;
    private boolean autoGenerated;
    private boolean confirmed;
    private LocalDateTime confirmedAt;

    private List<JournalLineResponse> lines;

    private BigDecimal totalDebit;
    private BigDecimal totalCredit;

}